services:
  freescout:
    image: tiredofit/freescout
    container_name: freescout
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:80"

  db:
    image: mariadb:10.6
    container_name: freescout-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: freescout
      MYSQL_USER: freescout
      MYSQL_PASSWORD: freescout
